### ISSUE TITLE
Lisp error: (invalid-function pyim-process-with-entered-buffer)

### ISSUE THREAD

**Issue by tekakutli** [tumashu/pyim#406]
**hello**, everything else seems to be working fine, but in the minibuffer instead of suggestions, this appears: 
pyim 出现错误: (invalid-function pyim-process-with-entered-buffer) , 开启 debug-on-error 后可以了解详细情况。

_it happens on any doc, "Newchinese" is just an almost empty test org-file_

Debugger message:
```
Debugger entered--Lisp error: (invalid-function pyim-process-with-entered-buffer)
  pyim-process-with-entered-buffer("#+TI TLE:  New chin ese\n \n\n秀秀 邮砂了入 也暗工要 熥为| \n")
  pyim-page-preview-create:xingma(nil)
  pyim-page-preview-create()
  pyim-page-style:two-lines(#<hash-table eql 5/65 0x13a5479>)
  pyim-page-refresh()
  pyim-process-run-1()
  pyim-process-run()
  pyim-self-insert-command()
  funcall-interactively(pyim-self-insert-command)
  call-interactively(pyim-self-insert-command)
  pyim-input-method-1(111)
  pyim-input-method(111)
```

My Doom config:
at packages.el
```
(package! pyim :recipe (:host github :repo "tumashu/pyim"))
(package! pyim-wbdict :recipe (:host github :repo "tumashu/pyim-wbdict"))
(package! pyim-basedict :recipe (:host github :repo "tumashu/pyim-basedict"))
```

at custom.el
```
(pyim-wbdict-v86-enable)
(setq default-input-method "pyim")
(setq pyim-default-scheme 'wubi)
```

thank you

**Comment by tumashu** [comment]
i think your pyim is outdated, try newest pyim code

在 2021-07-07 22:36:55，tekakutli ***@***.***> 写道：


hello, everything else seems to be working fine, but in the minibuffer instead of suggestions, this appears:
pyim 出现错误: (invalid-function pyim-process-with-entered-buffer) , 开启 debug-on-error 后可以了解详细情况。

it happens on any doc, "Newchinese" is just an almost empty test org-file

Debugger message:

Debugger entered--Lisp error: (invalid-function pyim-process-with-entered-buffer)

  pyim-process-with-entered-buffer("#+TI TLE:  New chin ese\n \n\n秀秀 邮砂了入 也暗工要 熥为| \n")

  pyim-page-preview-create:xingma(nil)

  pyim-page-preview-create()

  pyim-page-style:two-lines(#<hash-table eql 5/65 0x13a5479>)

  pyim-page-refresh()

  pyim-process-run-1()

  pyim-process-run()

  pyim-self-insert-command()

  funcall-interactively(pyim-self-insert-command)

  call-interactively(pyim-self-insert-command)

  pyim-input-method-1(111)

  pyim-input-method(111)



My Doom config:
at packages.el

(package! pyim :recipe (:host github :repo "tumashu/pyim"))

(package! pyim-wbdict :recipe (:host github :repo "tumashu/pyim-wbdict"))

(package! pyim-basedict :recipe (:host github :repo "tumashu/pyim-basedict"))



at custom.el

(pyim-wbdict-v86-enable)

(setq default-input-method "pyim")

(setq pyim-default-scheme 'wubi)



thank you
