### ISSUE TITLE
出字不准确

### ISSUE THREAD

**Issue by wanghuibin0** [tumashu/pyim#420]
不知道是不是我一个人的情况
我用全拼，但是打词组的时候，经常打出的字跟我输入的拼音对不上
比如我要打“径山寺”
![image](https://user-images.githubusercontent.com/14231615/144702334-ebbb0bdb-27db-42f4-8ba0-30581292e21b.png)
pyim打出来个“就是说”，跟拼音差了好远。

刚开始以为是模糊音的问题，把模糊音列表也清空了，还是不行。

我不知道这是个bug还是我哪里没有设置好？

**Comment by tumashu** [comment]
有这个功能，见 
https://github.com/tumashu/pyim/blob/e9fd048e338865de62df95eec20f6a83ff591428/pyim-candidates.el#L91 首字母联想

在 2021-12-04 16:03:01，hibert ***@***.***> 写道：


不知道是不是我一个人的情况
我用全拼，但是打词组的时候，经常打出的字跟我输入的拼音对不上
比如我要打“径山寺”

pyim打出来个“就是说”，跟拼音差了好远。

刚开始以为是模糊音的问题，把模糊音列表也清空了，还是不行。

我不知道这是个bug还是我哪里没有设置好？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghuibin0** [comment]
> 有这个功能，见 https://github.com/tumashu/pyim/blob/e9fd048e338865de62df95eec20f6a83ff591428/pyim-candidates.el#L91 首字母联想 在 2021-12-04 16:03:01，hibert ***@***.***> 写道： 不知道是不是我一个人的情况 我用全拼，但是打词组的时候，经常打出的字跟我输入的拼音对不上 比如我要打“径山寺” pyim打出来个“就是说”，跟拼音差了好远。 刚开始以为是模糊音的问题，把模糊音列表也清空了，还是不行。 我不知道这是个bug还是我哪里没有设置好？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以配置关掉吗？

**Comment by tumashu** [comment]
或许我应该把这个功能删除，好像没有想象的有用

在 2021-12-04 17:07:49，hibert ***@***.***> 写道：


有这个功能，见 https://github.com/tumashu/pyim/blob/e9fd048e338865de62df95eec20f6a83ff591428/pyim-candidates.el#L91 首字母联想 在 2021-12-04 16:03:01，hibert @.***> 写道： 不知道是不是我一个人的情况 我用全拼，但是打词组的时候，经常打出的字跟我输入的拼音对不上 比如我要打“径山寺” pyim打出来个“就是说”，跟拼音差了好远。 刚开始以为是模糊音的问题，把模糊音列表也清空了，还是不行。 我不知道这是个bug还是我哪里没有设置好？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以配置关掉吗？

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghuibin0** [comment]
> 或许我应该把这个功能删除，好像没有想象的有用 在 2021-12-04 17:07:49，hibert ***@***.***> 写道： 有这个功能，见 https://github.com/tumashu/pyim/blob/e9fd048e338865de62df95eec20f6a83ff591428/pyim-candidates.el#L91 首字母联想 在 2021-12-04 16:03:01，hibert @.***> 写道： 不知道是不是我一个人的情况 我用全拼，但是打词组的时候，经常打出的字跟我输入的拼音对不上 比如我要打“径山寺” pyim打出来个“就是说”，跟拼音差了好远。 刚开始以为是模糊音的问题，把模糊音列表也清空了，还是不行。 我不知道这是个bug还是我哪里没有设置好？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 可以配置关掉吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我觉得可以关掉，对于我来说，这个联想是个负担。
或者至少给个开关，能够自己配置。
再或者更智能一点，打全拼就不要联想，打简拼（只打声母）的时候再联想。

**Comment by tumashu** [comment]
功能删除了

**Comment by wanghuibin0** [comment]
> 功能删除了

高效！

**Comment by wanghuibin0** [comment]
> 功能删除了
melpa软件源一般多久会更新？

**Comment by tumashu** [comment]
估计需要半天吧？
