### ISSUE TITLE
提词框里出来的词序是倒的

### ISSUE THREAD

**Issue by lld2001** [tumashu/pyim#422]
五笔86词库，这是词库里搜索 ntk 这个编码：
![image](https://user-images.githubusercontent.com/8746632/145669672-e560370b-33c4-4e9e-a015-4554e07bf75a.png)

这是输入 ntk 时的提词框：
![image](https://user-images.githubusercontent.com/8746632/145669705-bee840cb-c0e9-4640-8d32-a1f326251120.png)

顺着词库来提示会否更好？

**Comment by tumashu** [comment]
我找个时间研究研究

在 2021-12-11 16:23:09，lld2001 ***@***.***> 写道：


五笔86词库，这是词库里搜索 ntk 这个编码：


这是输入 ntk 时的提词框：


顺着词库来提示会否更好？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tumashu** [comment]
试试吧，应该解决了

**Comment by lld2001** [comment]
可以了，👍。

我更新后，使用pyim-restart不起作用，要重启 emacs 才起作用。

**Comment by tumashu** [comment]
pyim-restart的问题应该解决了

**Comment by lld2001** [comment]
厉害。pyim输入法太好用了！
